### ISSUE TITLE
[bug] Segfault during long break

### ISSUE THREAD

**Issue by mjholub** [charlieroth/pomotui#4]
Reproducing:
0. Install with go install @latest
1. start pomotui, set short break to 5', long break to 20', 4 25-minute session cycle
2. When a long break is entered, stop, then continue
See the error:
```
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /home/me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:371 +0x95
panic({0x59a880, 0x6fda40})
        /usr/lib/go/src/runtime/panic.go:890 +0x262
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc0001280b0)
        /home/me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:540 +0x1276
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        /home/me/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:547
main.main()
        /home/me/go/pkg/mod/github.com/charlieroth/pomotui@v0.0.0-20220806094103-8ff7857b4e20/main.go:13 +0x8a
```
Judging from where the error occurs, this might be an upstream issue with bubbletea, but unlikely. 

On a side note, I'd love to see the support for skipping breaks or work sessions implemented, as well as restarting the counter (can contribute my time for that in near future as well).

Go env:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/me/go/bin"
GOCACHE="/home/me/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/me/go/pkg/mod"
GONOPROXY="github.com/italistdev"
GONOSUMDB="github.com/italistdev"
GOOS="linux"
GOPATH="/home/me/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build300346513=/tmp/go-build -gno-record-gcc-switches"
```
other relevant env vars:
```
$TERM: screen-256color (Alacritty with tmux on Wayland)
$SHELL: zsh
$OSTYPE: linux-musl
kernel version: 5.15.95-0-lts
```
I also think that the issue might be related to cgo having compatibility issues with musl, though given that go and alpine go kinda hand in hand in docker containers I also doubt it. I faced this issue way more often with rust crates that utilize the libc crate, this was also the reason I chose this program over rusty krab manager.

**Comment by charlieroth** [comment]
Hello @154pinkchairs! Thank you taking the time to submitting the issue :)

I don't know if I will have the time to take a deeper dive into this. If you would like to submit a pull request that fixes this issue, feel free. I will give it a quick review and merge if everything works. If I do find some time, I will create a pull request fixing this issue and update close this issue
